const express = require("express");
const cors = require("cors");
const router = express.Router();
router.use(cors());
const { OwnerRegistration } = require("../Controllers/OwnerRegistration");
const { OwnerLogin } = require("../Controllers/OwnerLogin");
const { AddService } = require("../Controllers/AddService");
const { GetService } = require("../Controllers/GetService");
const { DeleteService } = require("../Controllers/AddService");
const { OwnerForgetPassword } = require("../Controllers/ForgetPassword");
const { OwnerResetPassword } = require("../Controllers/ResetPassword");
const { DashBoardOwner } = require("../Controllers/OwnerDashboard");
const { UpdateService } = require("../Controllers/UpdateService");
const { AddPayment } = require("../Controllers/OwnerPayment");
const { GetPayment } = require("../Controllers/OwnerPayment");
const { UpdatePayment } = require("../Controllers/OwnerPayment");
const { GetPaymentRecord } = require("../Controllers/Payment");
router.post("/ownerSignup", OwnerRegistration);
router.post("/ownerLogin", OwnerLogin);
router.post("/serviceData", AddService);
router.get("/getService", GetService);
router.delete("/deleteService/:id", DeleteService);
router.post("/ownerForgetPassword", OwnerForgetPassword);
router.post("/ownerResetPassword/:id/:token", OwnerResetPassword);
router.post("/dashBoardOwner", DashBoardOwner);
router.put("/serviceUpdate/:id", UpdateService);
router.post("/addPayment", AddPayment);
router.get("/getPayment", GetPayment);
router.put("/updateCard/:id", UpdatePayment);
router.get("/getPaymentRecord", GetPaymentRecord);
// router.post("/forgetPassword", ForgetPassword);
// const { SearchHostel } = require("../Controllers/SearchHostel");
// router.post("/book", BookingHostel);
// router.post("./search", SearchHostel);
module.exports = router;
