const express = require("express");
const cors = require("cors");
const router = express.Router();
router.use(cors());
const { UserRegistration } = require("../Controllers/UserRegistration");
const { UserLogin } = require("../Controllers/UserLogin");
const { UserForgetPassword } = require("../Controllers/ForgetPassword");
const { UserResetPassword } = require("../Controllers/ResetPassword");
const { Payment } = require("../Controllers/Payment");
const { UserReviewData } = require("../Controllers/Review");
const { FindService } = require("../Controllers/FindHostel");
router.post("/signup", UserRegistration);
router.post("/login", UserLogin);
router.post("/userForgetPassword", UserForgetPassword);
router.post("/UserResetPassword/:id/:token", UserResetPassword);
router.post("/api/create-checkout-session", Payment);
router.post("/userReview", UserReviewData);
router.get("/find/:id", FindService);
module.exports = router;
