const express = require("express");
const cors = require("cors");
const router = express.Router();
router.use(cors());
const { UserRegistration } = require("../Controllers/UserRegistration");
const { UserLogin } = require("../Controllers/UserLogin");
const { BookingHostel } = require("../Controllers/BookingHostel");
const { UserForgetPassword } = require("../Controllers/ForgetPassword");
const { UserResetPassword } = require("../Controllers/ResetPassword");
// const { SearchHostel } = require("../Controllers/SearchHostel");
const { ServiceHostel } = require("../Controllers/FindHostel");
const { Payment } = require("../Controllers/Payment");
router.post("/signup", UserRegistration);
router.post("/login", UserLogin);
router.post("/book", BookingHostel);
router.post("/userForgetPassword", UserForgetPassword);
router.post("/UserResetPassword/:id/:token", UserResetPassword);
// router.post("/search", SearchHostel);
router.get("/find/:id", ServiceHostel);
router.post("/api/create-checkout-session", Payment);
module.exports = router;
